import {
  newDocumentSchema,
  ACCEPTED_DOCUMENT_FILE_TYPES,
  MAX_DOCUMENT_FILE_SIZE,
} from '$lib/store/newDocument';

const validValues = {
  title: 'Assurance 2026',
  number: 'INS-2026',
  documentableType: 'Truck',
  documentableId: '1',
  docType: '',
  issuedOn: '2026-01-01',
  expiresOn: '',
  file: new File(['content'], 'insurance.pdf', {type: 'application/pdf'}),
};

describe('newDocumentSchema', () => {
  it('passes with a valid PDF file and all required fields', async () => {
    await expect(
      newDocumentSchema.validate(validValues, {abortEarly: false})
    ).resolves.toBeDefined();
  });

  it('accepts every type in ACCEPTED_DOCUMENT_FILE_TYPES', async () => {
    for (const type of ACCEPTED_DOCUMENT_FILE_TYPES) {
      const file = new File(['content'], 'file', {type});
      await expect(
        newDocumentSchema.validate({...validValues, file}, {abortEarly: false})
      ).resolves.toBeDefined();
    }
  });

  it('rejects a missing file', async () => {
    const emptyFile = new File([], '');
    await expect(
      newDocumentSchema.validate({...validValues, file: emptyFile}, {abortEarly: false})
    ).rejects.toMatchObject({errors: expect.arrayContaining(['Le fichier est requis'])});
  });

  it('rejects a file type outside the accepted list', async () => {
    const file = new File(['content'], 'notes.txt', {type: 'text/plain'});
    await expect(
      newDocumentSchema.validate({...validValues, file}, {abortEarly: false})
    ).rejects.toMatchObject({
      errors: expect.arrayContaining([
        'Le fichier doit être un PDF, une image (JPEG, PNG, WebP), un document Word ou un fichier Excel',
      ]),
    });
  });

  it('rejects a file larger than MAX_DOCUMENT_FILE_SIZE', async () => {
    const file = new File(['content'], 'insurance.pdf', {type: 'application/pdf'});
    Object.defineProperty(file, 'size', {value: MAX_DOCUMENT_FILE_SIZE + 1});
    await expect(
      newDocumentSchema.validate({...validValues, file}, {abortEarly: false})
    ).rejects.toMatchObject({
      errors: expect.arrayContaining(['Le fichier ne doit pas dépasser 10 Mo']),
    });
  });

  it('accepts a file exactly at MAX_DOCUMENT_FILE_SIZE', async () => {
    const file = new File(['content'], 'insurance.pdf', {type: 'application/pdf'});
    Object.defineProperty(file, 'size', {value: MAX_DOCUMENT_FILE_SIZE});
    await expect(
      newDocumentSchema.validate({...validValues, file}, {abortEarly: false})
    ).resolves.toBeDefined();
  });

  it.each(['title', 'documentableType', 'documentableId', 'issuedOn'])(
    'rejects a missing %s',
    async (field) => {
      await expect(
        newDocumentSchema.validate({...validValues, [field]: ''}, {abortEarly: false})
      ).rejects.toBeDefined();
    }
  );

  it('accepts a blank expiresOn since it is optional', async () => {
    await expect(
      newDocumentSchema.validate({...validValues, expiresOn: ''}, {abortEarly: false})
    ).resolves.toBeDefined();
  });

  it('accepts a blank number since it is auto-generated by the backend', async () => {
    await expect(
      newDocumentSchema.validate({...validValues, number: ''}, {abortEarly: false})
    ).resolves.toBeDefined();
  });

  it('accepts an expiresOn on or after issuedOn', async () => {
    await expect(
      newDocumentSchema.validate(
        {...validValues, issuedOn: '2026-01-01', expiresOn: '2026-01-01'},
        {abortEarly: false}
      )
    ).resolves.toBeDefined();
  });

  it('rejects an expiresOn before issuedOn', async () => {
    await expect(
      newDocumentSchema.validate(
        {...validValues, issuedOn: '2026-06-01', expiresOn: '2026-01-01'},
        {abortEarly: false}
      )
    ).rejects.toMatchObject({
      errors: expect.arrayContaining([
        "La date d'expiration doit être postérieure à la date d'émission",
      ]),
    });
  });
});
